name: phylogenetic-datascience
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.9
  - jupyter
  - numpy
  - pandas
  - scipy
  - numba
  - loguru
  # - msprime>=1.0
  # - raxml
  # - toytree>=3.0
  - pip
  - pip:
    - git+https://github.com/eaton-lab/toytree.git@toy3#egg=toytree
