site_name: Phylogenetic Data Science (IN DEVELOPMENT)
repo_url: https://github.com/eaton-lab/phylogenetic-data-science
edit_uri: edit/master/docs/

theme: 
  name: material
  palette:
    - scheme: slate
      primary: teal
      # accent: orange
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
    - scheme: default
      # primary: teal
      # accent: orange
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
  favicon: docs/images/favicon.ico
  icon:
    logo: material/library

  features:
    - navigation.instant
    - navigation.tracking
    # - toc.integrate             # right-hav is always in toc
    - search.highlight
    - search.suggest
    - content.code.annotate # 
    # - navigation.indexes
    # - navigation.sections
    # - navigation.expand
    # - navigation.tabs.sticky

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js

extra:
  analytics:
    provider: google
    property: G-XXXXXXXXXX
  # version:
    # provider: mike

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - tables
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search

nav:
  - About/Ethos: index.md
  - Installation/Software: installation.md
  - Columbia course: course.md
  - 0 - Coding Bootcamp:
    - Getting started: bootcamp/getting-started.md
    - 0.0 - Installation (conda): bootcamp/0.0-installation-conda.md
    - 0.1 - Python Jupyter/Binder: bootcamp/0.1-jupyter-and-binder.md
    - 0.2 - Python types: bootcamp/0.2-python-types.md       # add link to vanderplas.
    - 0.3 - Python functions: bootcamp/0.3-python-funcs.md   # type hints at own link.
    - 0.4 - Python classes: bootcamp/0.4-python-classes.md   # 
    - 0.5 - Python style: bootcamp/0.5-python-style.md
    # - 0.6 - Python iterators: bootcamp/0.6-python-iterators.md
    # - 0.x - Python Data Science: bootcamp/python-datascience.md
    # - 0.x - Python Jit compilation: bootcamp/jit-compile.md
    # - 0.x - Python Algorithms: bootcamp/python-algorithms.md  # dynamic, iteration, 

  - 1 - Trees as data:
    - x.1 - Introduction: chapter-1/1.1-introduction.md
    - x.2 - Tree Thinking: chapter-1/1.2-tree-thinking.md
    - x.3 - Visualization: chapter-1/1.3-visualization.md
    - 1.4 - Trees as data: chapter-1/1.4-features-of-trees.md
    - 1.5 - Code - Node class: chapter-1/1.5-code-node-class.md
    - 1.6 - Code - Tree traversal: chapter-1/1.6-code-tree-traversal.md
    - 1.7 - Code - Tree class: chapter-1/1.7-code-tree-class.md
    - x.7 - Exercises: chapter-1/1.6-exercises.md

  - 2 - Trees as models:
    - x.0 - Tree as evolutionary models: chapter-2/2.0-tree-models.md
    - x.1 - Genealogies, Gene Trees, and Species Trees: y.md
    - x.2 - Tree Sequences and ARGs: z.md
    - x.3 - Genetic linkage?: linkm.md
    - Reading and Exercises: 1-reading-list.md

  - 3 - Genealogies:
    - 3.x - Modeling Evolution: chapter-3/3.x-modeling-HW.md
    - 3.0 - The Wright-Fisher Process: chapter-3/3.0-wright-fisher.md
    - 3.1 - Kingman Coalescent: chapter-3/3.1-coalescent.md
    - x.2 - Coalescent simulations (msprime): 3.2-msprime.md
    - x.3 - Demographic models: 3.3-demography.md
    - x.4 - Species Tree simulations (ipcoal): 3.4-ipcoal.md
    - x.x - Code - Coalescent probability: chapter-3/3.x-coalescent-probability.md
    - x.x - Code - MSC probability: chapter-3/3.x-MSC-probability.md
    - Exercises: chapter-3/3-reading-list.md
    - Further Reading: ...

  - 4 - Mutations:
    - x.0 - 'infinite-sites' mutations: 4.0-mutations.md
    - x.1 - Markov substitution models: 4.1-substituions.md
    # x.x - outgroups, orthology/homology, fixation.
    - x.2 - Statistical properties of Markov models: 4.2-markov-models.md
    - Reading and Exercises: 1-reading-list.md      

  - 5 - Data:
    - x.1 - data formats: 5.1-data-formats.md
    - x.2 - strings, tables, and matrices: 5.2-strings-and-matrices.md
    - x.3 - SNP data (variant call format): 5.3-variant
    - x.x - Code - simulating data/traits: x.x-simulating-traits.md
    - x.x - Code - sequence alignment: x.x-sequence-alignment.md
    - x.x - Code - converting file formats: x.x-converting-file-formats.md
    - Exercises: read, write, parse, find, and clean phylip, fasta, fastq, and vcf data.

  - 6 - Inference (Distance-based):
    - x.x - Distance based trees: ...
    - x.x - Code - UPGMA: ...
    - x.x - Code - Neighbor Joining: ...
    - Exercises: ...
    - Reading: ...

  - 7 - Inference (Parsimony):
    - x.0 - Maximum Parsimony: xx.md
    - x.1 - Scoring parsimony: yy.md
    - x.2 - Tree Space: yy.md
    - x.3 - Inferring: xx.ipynb
    - Reading and Exercises: 1-reading-list.md            

  - 8 - Inference (Likelihood):
    - x.0 - Maximum Likelihood: xx.md
    - x.1 - Genealogies: yy.md
    - x.2 - Sequences: yy.md
    - x.3 - Inferring: xx.ipynb
    - Reading and Exercises: 1-reading-list.md
